### ISSUE TITLE
AttributeError: 'QlikSenseCloudAutomationOperator' object has no attribute 'method'

### ISSUE THREAD

**Issue by Kaioken93** [tensor365/AIRFLOW-QLIKSENSE-CLOUD#4]
Hi,

I follow the step to setup a connection from airflow to qlikcloud.

But when I launch, airflow faild with this error :
AttributeError: 'QlikSenseCloudAutomationOperator' object has no attribute 'method'

Other thing strange : when I setup my connection, it was impossible to test it. the button still lock.

[dag_id=test-automation-report_run_id=manual__2024-10-08T13_13_59.496143+00_00_task_id=reload_automation_attempt=2.log](https://github.com/user-attachments/files/17294064/dag_id.test-automation-report_run_id.manual__2024-10-08T13_13_59.496143%2B00_00_task_id.reload_automation_attempt.2.log)

**Comment by tensor365** [comment]
Hello,

I'll check it. For test connection, I didn't implement yet the function. I'll add it this week end.

**Comment by tensor365** [comment]
I spot the bug , my bad I let a useless parameter. I commited the version. I'll push it on my pypi at the end of the day. Tell you when I did it.

**Comment by tensor365** [comment]
I added code to test connection tonight, i'll push in pypi tommrow afternoon if all test is ok. New version will correct the bug and add test connection button as the same time. Just need few more tests.

**Comment by Kaioken93** [comment]
Ok, thanks for the update, I will test monday if you push in pypi.

**Comment by tensor365** [comment]
Hi Kaioken93, 

Version 0.0.5 has been push to pypi this evening. I implemented test button but be careful by default, airflow deactivates the feature, you must activate it in your environnement setting. 

https://pypi.org/project/airflow-provider-qlik-sense-cloud/

One more point to care: 

conn_id parameter has been replace by qlik_sense_cloud_config_id parameter in all operators. 

So please try to recreate your Qlik Sense Connection and use qlik_sense_cloud_config_id instead of conn_id in all operators. 

Don't hesitate to tell me if you encounter any bug or if you need any another feature. I tested synchronous/asynchronous reload for app and automation.

**Comment by Kaioken93** [comment]
Hi,
I update pyp. I delete old connection and would like recreated a new conn as you suggest but now "Qlik sense cloud" disapeared of the list. They are no connexion for qlik. so may be something is deleted in your package ?

I have also an error mesage when airflow try to load my dag, maybe it can help you to fix th eissue :
![image](https://github.com/user-attachments/assets/cf86fd32-c435-4018-9229-f8d095366137)

Please find list with missig qlik connexion :
![image](https://github.com/user-attachments/assets/4a40e2e8-a0d7-4d3a-802c-1eaa6d479ebf)

The package is well installed on server :
![image](https://github.com/user-attachments/assets/0658eb0b-462e-447d-84d7-bf9e7088d3e7)

**Comment by tensor365** [comment]
Ok, you're using python 3.8, I will check but I think there is issues around hinting and in the new function, I added hinting on the return. I'll remove it to handle the retrocompatibility with python 3.8. I've made my test with python 3.10, and I didn't encountered this issue. I'll checki this evening.

**Comment by tensor365** [comment]
I spot the problem. In Python 3.8, Tuple hinting has to be declared with typing package. I'll will correct it this tonight and add airflow working with python 3.8 in my test and republish it on the same version. Sorry for the issue

**Comment by tensor365** [comment]
I published a new release, if you want to test. I'm installing a airflow with python 3.8 environment to test it too. But it'll take some time.

**Comment by Kaioken93** [comment]
Ok , let me know when i could update package.

**Comment by tensor365** [comment]
You can I already pushed a new version on 0.0.6

**Comment by tensor365** [comment]
I tested the installation on airflow 2.10 on Python 3.8 with the new version 0.0.6. Tested the test button connection, it seems to be ok. The Qlik Sense Connector displays correctly. Tell me if it's ok on your side

**Comment by tensor365** [comment]
Hello,

Tell me if you encounter any New issue

**Comment by Kaioken93** [comment]
Hello,

The connexion was done with succes 👍 

But now I have a strange faild when I launch automation.

I test 2 times. First test with setup 1 retry.
Airflow trigger well Qlik. But after 4 minutes it's faild in airflow while continue well in Qlik
Because I set up retry 1 time, airflow re-trigger Qlik.
So Qlik finish the first time well and immediatly relauch the automation.
Airflow monitor well the retry with no faild.

I try a second time without retry set up, and airflow mark as faild after 10 minutes, while in Qlik the automation task finish well without a faild.

Please find airflow log :

Fake failed : [dag_id=test-automation-report_run_id=manual__2024-10-15T09_52_48.940516+00_00_task_id=reload_automation_attempt=1.log](https://github.com/user-attachments/files/17381209/dag_id.test-automation-report_run_id.manual__2024-10-15T09_52_48.940516%2B00_00_task_id.reload_automation_attempt.1.log)

Ok : [dag_id=test-automation-report_run_id=manual__2024-10-15T09_52_48.940516+00_00_task_id=reload_automation_attempt=2.log](https://github.com/user-attachments/files/17381215/dag_id.test-automation-report_run_id.manual__2024-10-15T09_52_48.940516%2B00_00_task_id.reload_automation_attempt.2.log)



Fake failed : [dag_id=test-automation-report_run_id=manual__2024-10-15T11_59_35.647487+00_00_task_id=reload_automation_attempt=1.log](https://github.com/user-attachments/files/17381206/dag_id.test-automation-report_run_id.manual__2024-10-15T11_59_35.647487%2B00_00_task_id.reload_automation_attempt.1.log)

**Comment by tensor365** [comment]
Hi,

Looking your logs and coming back to you. It's strange because I can't reproduce on my side. My automation only contained a sleep operator.

**Comment by tensor365** [comment]
It seems to come from Qlik python sdk. I'll fix it tonight and push a new version. Telling you when I did it.

**Comment by tensor365** [comment]
Sorry, I don't know if your tenant is in ireland. But it seems Qlik cloud had some trouble about reload today. Can you check if you have the bug again ? Maybe we have been unlucky and the bug affects your test. 

Qlik Cloud – AWS – Europe (Ireland): Reload Performance Issues
New incident: Investigating
We are investigating potential performance issues with reloads, which may result in slower loading times or intermittent timeouts. Our team is investigating the cause and working towards a prompt resolution.

**Comment by Kaioken93** [comment]
Hello,
I try 2 times, and the 2 passed well.

Thanks for your great job and support  👍 💯

**Comment by tensor365** [comment]
Glad to help you. Don't hesitate if you need further feature.
